shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specs/', include('specs.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

specs/urls.py
from django.urls import path

from .views import (
    BaseSpecView,
    CreateNewFeature,
    CreateNewCategory,
    CreateNewFeatureValidator,
    FeatureChoiceView,
    CreateFeatureView,
    NewProductFeatureView,
    SearchProductAjaxView,
    AttachNewFeatureToProduct,
    ProductFeatureChoicesAjaxView,
    CreateNewProductFeatureAjaxView,
    UpdateProductFeaturesView,
    ShowProductFeaturesForUpdate,
    UpdateProductFeaturesAjaxView
)

urlpatterns = [
    path('', BaseSpecView.as_view(), name='product-list-for-features'),
    path('new-feature/', CreateNewFeature.as_view(), name='new-feature'),
    path('new-category/', CreateNewCategory.as_view(), name='new-category'),
    path('new-validator/', CreateNewFeatureValidator.as_view(), name='new-validator'),
    path('feature-choice/', FeatureChoiceView.as_view(), name='feature-choice-validators'),
    path('feature-create/', CreateFeatureView.as_view(), name='create-feature'),
    path('new-product-feature/', NewProductFeatureView.as_view(), name='new-product-feature'),
    path('search-product/', SearchProductAjaxView.as_view(), name='search-product'),
    path('attach-feature/', AttachNewFeatureToProduct.as_view(), name='attach-feature'),
    path('product-feature/', ProductFeatureChoicesAjaxView.as_view(), name='product-feature'),
    path('attach-new-product-feature/', CreateNewProductFeatureAjaxView.as_view(), name='attach-new-product-feature'),
    path('update-product-features/', UpdateProductFeaturesView.as_view(), name='update-product-features'),
    path('show-product-features-for-update/', ShowProductFeaturesForUpdate.as_view(), name='show-product-features-for-update'),
    path('update-product-features-ajax/', UpdateProductFeaturesAjaxView.as_view(), name='update-product-features-ajax')
]

specs/models.py
from django.db import models


class CategoryFeature(models.Model):

    category = models.ForeignKey("mainapp.Category", verbose_name='Категория', on_delete=models.CASCADE)
    feature_name = models.CharField(verbose_name='Имя ключа для категории', max_length=50)
    feature_filter_name = models.CharField(verbose_name='Имя для фильтра', max_length=50)
    unit = models.CharField(max_length=50, verbose_name='Единица измерения', null=True, blank=True)

    class Meta:
        unique_together = ('category', 'feature_name', 'feature_filter_name')

    def __str__(self):
        return f"{self.category.name} | {self.feature_name}"


class FeatureValidator(models.Model):

    category = models.ForeignKey("mainapp.Category", verbose_name='Категория', on_delete=models.CASCADE)
    feature_key = models.ForeignKey(CategoryFeature, verbose_name='Ключ характеристики', on_delete=models.CASCADE)
    valid_feature_value = models.CharField(max_length=100, verbose_name='Валидное значение')

    def __str__(self):
        return f"Категория {self.category.name} | " \
               f"Характристика {self.feature_key.feature_name} | " \
               f"Валидное значение {self.valid_feature_value}"


class ProductFeatures(models.Model):

    product = models.ForeignKey("mainapp.Product", verbose_name='Товар', on_delete=models.CASCADE)
    feature = models.ForeignKey(CategoryFeature, verbose_name='Характеристика', on_delete=models.CASCADE)
    value = models.CharField(max_length=255, verbose_name='Значение')

    def __str__(self):
        return f"Товар - {self.product.title} | " \
               f"Характеристика - {self.feature.feature_name} | " \
               f"Значение - {self.value}"

specs/forms.py
from django import forms

from .models import FeatureValidator, CategoryFeature
from mainapp.models import Category


class NewCategoryFeatureKeyForm(forms.ModelForm):

    class Meta:
        model = CategoryFeature
        fields = '__all__'


class NewCategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'


class FeatureValidatorForm(forms.ModelForm):

    class Meta:
        model = FeatureValidator
        fields = ['category']

specs/views.py
from collections import defaultdict

from django.contrib import messages
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect, JsonResponse

from .models import CategoryFeature, FeatureValidator, ProductFeatures
from .forms import NewCategoryFeatureKeyForm, NewCategoryForm
from mainapp.models import Category, Product


class BaseSpecView(View):

    def get(self, request, *args, **kwargs):
        return render(request, 'product_features.html', {})


class CreateNewFeature(View):

    def get(self, request, *args, **kwargs):
        form = NewCategoryFeatureKeyForm(request.POST or None)
        context = {'form': form}
        return render(request, 'new_feature.html', context)

    def post(self, request, *args, **kwargs):
        form = NewCategoryFeatureKeyForm(request.POST or None)
        if form.is_valid():
            new_category_feature_key = form.save(commit=False)
            new_category_feature_key.category = form.cleaned_data['category']
            new_category_feature_key.feature_name = form.cleaned_data['feature_name']
            new_category_feature_key.save()
        return HttpResponseRedirect('/product-specs/')


class CreateNewCategory(View):

    def get(self, request, *args, **kwargs):
        form = NewCategoryForm(request.POST or None)
        context = {'form': form}
        return render(request, 'new_category.html', context)

    def post(self, request, *args, **kwargs):
        form = NewCategoryForm(request.POST or None)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.name = form.cleaned_data['name']
            new_category.save()
        return HttpResponseRedirect('/product-specs/')


class CreateNewFeatureValidator(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'new_validator.html', context)


class FeatureChoiceView(View):

    def get(self, request, *args, **kwargs):
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="feature-validators" id="feature-validators-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        feature_key_qs = CategoryFeature.objects.filter(
            category_id=int(request.GET.get('category_id'))
        )
        res_string = ""
        for item in feature_key_qs:
            res_string += option.format(value=item.feature_name, option_name=item.feature_name)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"result": html_select, "value": int(request.GET.get('category_id'))})


class CreateFeatureView(View):

    def get(self, request, *args, **kwargs):
        category_id = request.GET.get('category_id')
        feature_name = request.GET.get('feature_name')
        value = request.GET.get('feature_value').strip(" ")
        print(value)
        category = Category.objects.get(id=int(category_id))
        feature = CategoryFeature.objects.get(category=category, feature_name=feature_name)
        existed_object, created = FeatureValidator.objects.get_or_create(
            category=category,
            feature_key=feature,
            valid_feature_value=value
        )
        if not created:
            return JsonResponse({
                "error": f"Значение '{value}' уже существует."
            })
        messages.add_message(
            request, messages.SUCCESS,
            f'Значение "{value}" для характеристики '
            f'"{feature.feature_name}" в категории {category.name} успешно создано'
        )
        return JsonResponse({'result': 'ok'})


class NewProductFeatureView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'new_product_feature.html', context)


class SearchProductAjaxView(View):

    def get(self, request, *args, **kwargs):
        query = request.GET.get('query')
        category_id = request.GET.get('category_id')
        category = Category.objects.get(id=int(category_id))
        products = list(Product.objects.filter(
            category=category,
            title__icontains=query
        ).values())
        return JsonResponse({"result": products})


class AttachNewFeatureToProduct(View):

    def get(self, request, *args, **kwargs):
        res_string = ""
        product = Product.objects.get(id=int(request.GET.get('product_id')))
        existing_features = list(set([item.feature.feature_name for item in product.features.all()]))
        print(existing_features)
        category_features = CategoryFeature.objects.filter(
            category=product.category
        ).exclude(feature_name__in=existing_features)
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="product-category-features" id="product-category-features-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        for item in category_features:
            res_string += option.format(value=item.category.id, option_name=item.feature_name)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"features": html_select})


class ProductFeatureChoicesAjaxView(View):

    def get(self, request, *args, **kwargs):
        res_string = ""
        category = Category.objects.get(id=int(request.GET.get('category_id')))
        feature_key = CategoryFeature.objects.get(
            category=category,
            feature_name=request.GET.get('product_feature_name')
        )
        validators_qs = FeatureValidator.objects.filter(
            category=category,
            feature_key=feature_key
        )
        option = '<option value="{value}">{option_name}</option>'
        html_select = """
            <select class="form-select" name="product-category-features-choices" id="product-category-features-choices-id" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        for item in validators_qs:
            res_string += option.format(value=item.id, option_name=item.valid_feature_value)
        html_select = html_select.format(result=res_string)
        return JsonResponse({"features": html_select})


class CreateNewProductFeatureAjaxView(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(title=request.GET.get('product'))
        category_feature = CategoryFeature.objects.get(
            category=product.category,
            feature_name=request.GET.get('category_feature')
        )
        value = request.GET.get('value')
        feature = ProductFeatures.objects.create(
            feature=category_feature,
            product=product,
            value=value
        )
        product.features.add(feature)
        return JsonResponse({"OK": "OK"})


class UpdateProductFeaturesView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {'categories': categories}
        return render(request, 'update_product_features.html', context)


class ShowProductFeaturesForUpdate(View):

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(id=int(request.GET.get('product_id')))
        features_values_qs = product.features.all()
        head = """
        <hr>
            <div class="row">
                <div class="col-md-4">
                    <h4 class="text-center">Характеристика</h4>
                </div>
                <div class="col-md-4">
                    <h4 class="text-center">Текущее значение</h4>
                </div>
                <div class="col-md-4">
                    <h4 class="text-center">Новое значение</h4>
                </div>
            </div>
        <div class='row'>{}</div>
        <div class="row">
        <hr>
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <p class='text-center'><button class="btn btn-success" id="save-updated-features">Сохранить</button></p> 
        </div>
        <div class="col-md-4">
        </div>
        </div>
        """
        option = '<option value="{value}">{option_name}</option>'
        select_values = """
            <select class="form-select" name="feature-value" id="feature-value" aria-label="Default select example">
                <option selected>---</option>
                {result}
            </select>
                    """
        mid_res = ""
        select_different_values_dict = defaultdict(list)
        for item in features_values_qs:
            fv_qs = FeatureValidator.objects.filter(
                category=item.product.category,
                feature_key=item.feature
            ).values()
            for fv in fv_qs:
                if fv['valid_feature_value'] == item.value:
                    pass
                else:
                    select_different_values_dict[fv['feature_key_id']].append(fv['valid_feature_value'])
            feature_field = '<input type="text" class="form-control" id="{id}" value="{value}" disabled/>'
            current_feature_value = """
            <div class='col-md-4 feature-current-value' style='margin-top:10px; margin-bottom:10px;'>{}</div>
                                    """
            body_feature_field = """
            <div class='col-md-4 feature-name' style='margin-top:10px; margin-bottom:10px;'>{}</div>
                                """
            body_feature_field_value = """

specs/templates/mass_add_features.html
{% extends 'product_features.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="category-validator-div">
    <label for="category-validators-id">Категория</label>
    <select class="form-select" name="category-validators" id="category-validators-id" aria-label="Default select example">
    <option selected>---</option>
        {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
</div>
    <div class="product-search-ajax" style="display: none; margin-top: 20px;">
      <div class="form-group">
        <label for="search-text">Поиск товара</label>
        <input type="text" name='search-text' class="form-control" id="search-text" aria-describedby="emailHelp" placeholder="Введите слова для поиска">
      </div>
    </div>
    <div class="search-results">
        <ul class="list-group" id="no-results" style="display: none">
            <li class="list-group-item list-group-item-light">По вашему запросу результатов не найдено</li>
        </ul>
        <ul class="list-group" id="search-product-results" style="padding-top: 10px;">
        </ul>
    </div>
<div class="product" style="margin-top: 30px;">
</div>
<div class="product-feature-choices">

</div>
<input type="submit" class="btn btn-success" value="Создать" style="display: none; margin-top: 10px;" id="create-product-feature">
{% endblock %}
{% block massfeatures %}
<div class="product-features" style="margin-top: 10px;">
</div>
{% endblock massfeatures %}
{% block js %}
<script>
    $(document).on('click', "#create-product-feature", function (){
        let product = $("#product-title").text()
        let category_feature = $("#product-category-features-id option:selected").text()
        let value = $("#product-category-features-choices-id option:selected").text()
        let data = {
            product: product,
            category_feature: category_feature,
            value: value
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: '/product-specs/attach-new-product-feature/',
            success: function (data){
                $(".product-features").append(data.result)
            }
        })
    })
    function removeProduct(){
        $(".search-results").css('display', 'block')
        $(".product-search-ajax").css('display', 'block')
        $(".product-feature-choices").empty()
        $(".product-feature-choices-values").empty()
    }
    function getProduct(productId, title){
        $('.product').append(
            '<div class="alert alert-info alert-dismissible show" id="product-title" role="alert">' + title +
            '<button type="button" onclick="removeProduct()" ' +
            'class="btn-close" data-bs-dismiss="alert" aria-label="Close">' +
            '</button>' +
            '</div>'
        )
        $(".search-results").css('display', 'none')
        $("#search-product-results").empty()
        $(".product-search-ajax").css('display', 'none')
        $(".product-feature-choices").css('display', 'block')
        $(".product-feature-choices-values").css('display', 'block')
        $('input[name="search-text"]').val("")
        let category_id = $('select[name="category-validators"]').val()
        let data = {
            product_id: productId,
            category_id: category_id
        }
        $.ajax({
            method: "GET",
            data:data,
            dataType: "json",
            url: "/product-specs/show-all-category-features-ajax/",
            success: function (data){
                $(".product-features").append(data.result)
            }
        })
    }
    $(document).on('change', 'select[name="product-category-features"]', function (){
        let data = {
            category_id: this.value,
            product_feature_name: $("#product-category-features-id option:selected").text()
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: "/product-specs/product-feature/",
            success: function (data){
                $(".product-feature-choices-values").append(data.features)
            }
        })
    })
    $(document).on('change', 'select[name="product-category-features-choices"]', function (){
        $("#create-product-feature").css('display', 'block')
    })
    $('select[name="category-validators"]').on('change', function() {
    $(".product").empty()
    $(".errors").empty()
    $("#search-product-results").empty()
    $(".product-search-ajax").css('display', 'block')
    });
    $('input[name="search-text"]').on('input', function(){
    if(this.value.length == 0){
        $(".search-results").css('display', 'none')
    }else{
        $(".search-results").css('display', 'block')
    }
    $("#search-product-results").empty()
    let data = {
        query: this.value,
        category_id: $('select[name="category-validators"] option').filter(':selected').val()
    }

    $.ajax({
    method: "GET",
    dataType: "json",
    data: data,
    url: "/product-specs/search-product/",
    success: function(data){
        let items = []
        if(data.result.length < 1){
            $('#no-results').css('display', 'block')
        }else{
            $('#no-results').css('display', 'none')
        }
        $.each(data, function (index, value) {
            $.each(value, function (idx, v){
                if($.inArray(v, items) == -1){
                    items.push(v)
                    $('#search-product-results').append(
                        '<li class="list-group-item list-group-item-action" ' +
                        'onclick="getProduct(\'' + v.id + '\', \'' + v.title + '\')" ' +
                        'style="cursor: pointer" id="product-' +
                        v.id + '">'
                        + v.title +
                        ' | ' +
                        v.price +
                        ' руб.' +
                        '</li>')
                        }
                    })
                })
            }
        })
    })
</script>
{% endblock js %}

specs/templates/new_category.html
{% extends 'product_features.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-12">
        <form action="{% url 'new-category' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
        <input type="submit" class="btn btn-success" value="Создать">
        </form>
    </div>
{% endblock %}

specs/templates/new_feature.html
{% extends 'product_features.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form action="{% url 'new-feature' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
<input type="submit" class="btn btn-success" value="Создать">
</form>
{% endblock %}

specs/templates/new_validator.html
{% extends 'product_features.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="category-validator-div">
    <label for="category-validators-id">Категория</label>
    <select class="form-select" required name="category-validators" id="category-validators-id" aria-label="Default select example">
    <option selected>---</option>
        {% for category in categories %}
          <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
</div>
<div class="feature-validator-div" style="display: None; padding-top: 20px;">
</div>
<div class="feature-value-div" style="padding-top: 20px;">

</div>
<div class="errors">

</div>
{% endblock %}

specs/templates/product_features.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Title</title>
</head>
<style>
    #id_category {
        width: 200px;
        margin-right: 15px;
    }
    #id_feature_key_name {
        width: 400px;
        margin-right: 15px;
    }
</style>
<body>
<div class="container">
<h3 class="text-center">Админка характеристик</h3>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
<div class="row">
    <div class="col-md-4">
<div class="list-group">
    <a href="{% url 'new-category' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specs/new-category/" %}active{% endif %}" aria-current="true">
    Создать новую категорию
  </a>
  <a href="{% url 'new-feature' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specs/new-feature/" %}active{% endif %}" aria-current="true">
    Создать новую характеристику
  </a>
    <a href="{% url 'new-validator' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specs/new-validator/" %}active{% endif %}" aria-current="true">
    Создать значение характеристики
  </a>
    <a href="{% url 'new-product-feature' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specs/new-product-feature/" %}active{% endif %}" aria-current="true">
    Создать характеристику для товара
    <a href="{% url 'update-product-features' %}" class="list-group-item list-group-item-action {% if request.path == "/product-specs/update-product-features/" %}active{% endif %}" aria-current="true">
    Редактировать характеристику для товара
  </a>
</div>
    </div>
    <div class="col-md-8">
    {% block content %}
    {% endblock %}

    </div>
</div>
{% block productfeaturesupdate %}
{% endblock productfeaturesupdate %}
{% block massfeatures %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
{% block js %}
<script>
        $('select[name="category-validators"]').on('change', function() {
        var categoryId = this.value;
        data = {
            category_id: categoryId
        }
        prev_choice = categoryId
        $(".feature-validator-div").empty()
        $(".feature-value-div").empty()
        $(".errors").empty()
        $.ajax({
            method: "GET",
            dataType: "json",
            data: data,
            url: "/product-specs/feature-choice/",
            success: function(data){
                $(".feature-validator-div").css('display', 'block');
                $(".feature-validator-div").append(data['result'])
            }
        })
    });
    $(document).on('change', 'select[name="feature-validators"]', function(){
        $('.feature-value-div').empty()
        $('.errors').empty()
        $('.feature-value-div').append(
            '<input type="text" class="form-control" id="feature-value" required></input>',
            '<br>',
            '<input type="submit" class="btn btn-success" id="create-validator" value="Создать">'
        )
    })
</script>
<script>
    $(document).on('click', '#create-validator', function (){
        var catgoryId = $("#category-validators-id").val();
        var featureName = $("#feature-validators-id").val();
        var featureValue = $("#feature-value").val()
        data = {
            category_id: catgoryId,
            feature_name: featureName,
            feature_value: featureValue
        }
        $.ajax({
            method: "GET",
            dataType: "json",
            data:data,
            url: "/product-specs/feature-create/",
            success: function (data){
                if('error' in data){
                    $('.errors').append(
                        '<p class="text-center" style="color:red;"><strong>' + data['error'] + '</strong></p>'
                    )
                }else{
                    console.log('asdasdasdasdasd')
                    window.location.href="/product-specs/"
                }
            }
        })
    })
</script>
{% endblock js %}
</body>
</html>